update workflow

diff --git a/.github/workflows/publish.apps.yml b/.github/workflows/publish.apps.yml
--- a/.github/workflows/publish.apps.yml
+++ b/.github/workflows/publish.apps.yml
@@ -88,11 +88,6 @@ jobs:
       - name: 🧩 Install Dependencies
         run: npm ci
 
-      - name: 🔢 Set Version and Build Number
-        run: |
-          npm version ${{ github.event.inputs.releaseType }} --no-git-tag-version
-          npm run build.version.android
-
       - name: 🏗️ Build Android Release
         run: npm run android.release
 
@@ -130,11 +125,6 @@ jobs:
 
       - name: 🧩 Install Dependencies
         run: npm ci
-
-      - name: 🔢 Set Version and Build Number
-        run: |
-          npm version ${{ github.event.inputs.releaseType }} --no-git-tag-version
-          npm run build.version.ios
       
       # This is temp to fix the issue
       # "error Cannot start server in new window because no terminal app was specified."
@@ -183,6 +173,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: pre-release
+          fetch-depth: 0 
 
       - name: 🌲 Setup Git
         run: |
@@ -191,28 +182,38 @@ jobs:
 
       - name: 🔖 Tag New Release
         run: |
-          git tag -a "v${{ needs.prepare_release.outputs.new_version }}" -m "Release v${{ needs.prepare_release.outputs.new_version }}"
-          git push origin "v${{ needs.prepare_release.outputs.new_version }}"
+          git tag -a "${{ needs.prepare_release.outputs.new_version }}" -m "Release ${{ needs.prepare_release.outputs.new_version }}"
+          git push origin "${{ needs.prepare_release.outputs.new_version }}"
 
       - name: 🔀 Merge Pre-Release to Main
         run: |
           git fetch
           git checkout main
-          git merge --no-ff pre-release -m "Merging pre-release to main: Release v${{ needs.prepare_release.outputs.new_version }}"
+          git merge --no-ff pre-release -m "Merging pre-release to main: Release ${{ needs.prepare_release.outputs.new_version }}" || echo "Merge failed, printing diffs next."
           git push origin main
+        continue-on-error: true
+
+      - name: 🕵️ Print Diffs if Merge Fails
+        if: failure()
+        run: |
+          echo "Printing diffs between main and pre-release..."
+          git diff main pre-release
+          echo "diffs_printed=true" >> $GITHUB_ENV        
 
       - name: 🚀 Create GitHub Release
         id: create_release
+        if: env.diffs_printed != 'true'
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: v${{ needs.prepare_release.outputs.new_version }}
-          release_name: Release v${{ needs.prepare_release.outputs.new_version }}
-          draft: false
+          tag_name: ${{ needs.prepare_release.outputs.new_version }}
+          release_name: Release ${{ needs.prepare_release.outputs.new_version }}
+          draft: true
           prerelease: false
 
       - name: 📤 Upload Artifacts to Release
+        if: env.diffs_printed != 'true'
         run: |
           ASSET_URL=${{ steps.create_release.outputs.upload_url }}
           echo "Uploading Android App..."
